# Generated by Django 3.2.7 on 2021-11-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211123_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '章节信息', 'verbose_name_plural': '章节信息'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '章节视频', 'verbose_name_plural': '章节视频'},
        ),
    ]
