# Generated by Django 3.2.7 on 2021-12-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
    ]
